---
- name: Deploy DB Service
  hosts: db_servers
  become: true
  tasks:
    - name: Pull DB Service Docker image
      docker_image:
        name: "{{ db_image }}"
        source: pull

    - name: Run DB Service container
      docker_container:
        name: my-db-service
      image: "{{ db_image }}"
      ports:
        - "{{ db_port }}:5432"
      state: started
      restart_policy: always